name: kunhavigi_client
description: Starting point for a Serverpod client.

resolution: workspace

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  serverpod_client: 2.9.1
  kunhavigi_shared:
    path: ../kunhavigi_shared
