services:
  server:
    build: .
    depends_on:
      - postgres
      - redis
      - tailscale
    environment:
      - DATA_DIRECTORY=/app/data
    volumes:
      - /mnt/hdd-data:/app/data  # ハードディスクのデータなどを指定すると良い
      # - ./data:/app/data
    networks:
      kunhavigi_net:
        ipv4_address: 172.24.0.10

  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: kunhavigi
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - kunhavigi_data:/var/lib/postgresql/data
    networks:
      - kunhavigi_net

  redis:
    image: redis:6.2.6
    command: redis-server
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - kunhavigi_net

  tailscale:
    image: tailscale/tailscale:latest
    hostname: kunhavigi
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_ROUTES=172.24.0.0/24
      # - TS_EXTRA_ARGS=--advertise-tags=tag:container
      # - TS_USERSPACE=false
    volumes:
      - ${PWD}/tailscale/state:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: unless-stopped
    networks:
      - kunhavigi_net

networks:
  kunhavigi_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.24.0.0/24

volumes:
  kunhavigi_data: