name: kunhavigi_server
description: Starting point for a Serverpod server.
# version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  kunhavigi_shared:
    path: ../kunhavigi_shared
  path: ^1.9.1
  serverpod: 2.9.1

dev_dependencies:
  lints: ">=3.0.0 <7.0.0"
  serverpod_test: 2.9.1
  test: "^1.24.2"
  very_good_analysis: ^9.0.0
