type: server

client_package_path: ../kunhavigi_client
server_test_tools_path: test/integration/test_tools

extraClasses:
  - package:kunhavigi_shared/kunhavigi_shared.dart:Entry
  - package:kunhavigi_shared/kunhavigi_shared.dart:FileEntry
  - package:kunhavigi_shared/kunhavigi_shared.dart:EntryPreview
